blank_issues_enabled: false
contact_links:
  - name: Question or problem with Hydra
    url: https://github.com/Smithsonian/hydra/blob/main/docs/policies/index.md#getting-help
    about: For help with the cluster itself, email SI-HPC@si.edu. Issues here are about the documentation site.
