#!/usr/bin/env bash
# Regenerate docs/software/module-list.md from the live module tree.
# Run on a Hydra login node, commit the result through a PR:
#
#   ./scripts/gen_module_list.sh > docs/software/module-list.md
#
# A weekly cron on hydra-login04 (/home/hpc/bin/check_module_list.sh) fetches
# this script from the repo, runs it, and mails SI-HPC-Admin when the result
# differs from the committed page, so the output must be deterministic: no dates,
# hostnames, or per-user state (the <L> and <S> tags module puts on modules the
# running user has loaded are stripped below).
set -euo pipefail
PREFIXES="${*:-bio tools}"   # module prefixes to list, in order

cat << 'HDR'
# Installed modules

<!-- Generated by scripts/gen_module_list.sh; do not edit by hand. -->

This list is generated from `module -t avail`. Load a package with `module load PREFIX/NAME/VERSION`; `(default)` marks the version loaded when no version is given. The prefix `bioinformatics/` is an alias of `bio/`. The compilers and their MPI builds (`gcc/`, `intel/`, `nvidia/`) are under [Compilers, libraries and MPI](compilers.md); the [list of module files](https://hydra.si.edu/tools/QSubGen/module-avail.html) (SI network or VPN) is the complete inventory, including versions this list omits.
HDR

for PREFIX in $PREFIXES; do
  printf '\n## `%s/`\n\n| Module | Versions |\n|---|---|\n' "$PREFIX"
  module -t avail "${PREFIX}" 2>&1 \
    | grep -E "^${PREFIX}/" \
    | sed -E "s#^${PREFIX}/##; s# *<[A-Za-z]+>##g" \
    | awk -F/ '{ name=$1; ver=(NF>1)?substr($0, length(name)+2):"";
                 if (!((name SUBSEP ver) in seen)) { seen[name SUBSEP ver]=1; v[name]=(name in v)?v[name] ", " ver:ver } }
               END { for (n in v) print "| `" n "` | " v[n] " |" }' \
    | sort -t '`' -k2,2f
done